trigger:
  branches:
    include:
      - main
      - develop

variables:
  Docker.Image.Name: demo-devops

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: build
    jobs:
      - job: 'CI'
        displayName: 'Build'
        steps:
          - checkout: self

          - task: SonarCloudPrepare@1
            displayName: 'SonarCloud Prepare'
            inputs:
              SonarCloud: "SonarCloud GitHub"
              organization: "sancanoga"
              scannerMode: "Other"
              extraProperties: |
                  sonar.projectKey=sancanoga_demo-devops
                  sonar.projectName=demo-devops
                  sonar.branch.name=main

          - task: Gradle@2
            displayName: 'Build Project'
            inputs:
              gradleWrapperFile: "gradlew"
              tasks: "build -x test"
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.11"
              sonarQubeRunAnalysis: false
              spotBugsAnalysis: false

          - task: Gradle@2
            displayName: 'Unit Tests'
            inputs:
              gradleWrapperFile: "gradlew"
              tasks: "test"
              publishJUnitResults: true
              testResultsFiles: "**/TEST-*.xml"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.11"
              testRunTitle: UnitTests Results
              sonarQubeRunAnalysis: true
              spotBugsAnalysis: true

          - task: SonarCloudPublish@1
            displayName: 'SonarCloud Publish'
            inputs:
              pollingTimeoutSec: "300"

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              ArtifactName: 'artifact'
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/libs'
        
