name: Imprimir valor de secreto en ambiente DEV

on:
  push:
    branches:
      - main

jobs:
  print-secret-value:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Imprimir valor de secreto
      run: |
        echo "El valor del secreto CONSUL_TOKEN en el ambiente DEV es: ${{ secrets.CONSUL_TOKEN }}"
