name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build
      run: ./gradlew build -x test

    - name: Unit Test
      run: ./gradlew test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: sancanoga/demo-devops:latest


  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl launch --name demo-devops --image sancanoga/demo-devops:latest --now
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN }}
