name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'oracle'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
  
    - name: Build
      run: ./gradlew build -x test

    - name: Unit Test
      run: ./gradlew test
